language: python

matrix:
 include: 
    - stage: Test
      python: 3.7
      os: linux
      dist: xenial
      script: ./.travis_test.sh
      script: coveralls
    - stage: Test
      python: 3.6
      os: linux
      dist: xenial
      script: ./.travis_test.sh
      script: coveralls
    - stage: Test
      env: CC=gcc PYTHON_VERSION='3.7'
      language: generic
      os: osx
      script: ./.travis_test.sh
      script: coveralls
    - stage: Deploy
      python: 3.7
      os: linux
      dist: xenial
      script: ./.travis_deploy.sh

before_install:
  - ./.travis_before_install.sh

install:
  - ./.travis_install.sh
