language: python

stages:
  - Test
  - Deploy
  - Test_deployed

matrix:
 include: 
    - stage: Test
      python: 3.8
      os: linux
      dist: bionic
      script: ./.travis_test.sh
      script: coveralls
    - stage: Test
      python: 3.7
      os: linux
      dist: xenial
      script: ./.travis_test.sh
      script: coveralls
    - stage: Test
      python: 3.6
      os: linux
      dist: xenial
      script: ./.travis_test.sh
      script: coveralls
    - stage: Test
      env: CC=gcc CONDA_PY='3.8'
      language: generic
      os: osx
      script: ./.travis_test.sh
      osx_image: xcode11
    - stage: Test
      env: CC=gcc CONDA_PY='3.7'
      language: generic
      os: osx
      script: ./.travis_test.sh
      osx_image: xcode11
    - stage: Deploy
      if: tag =~ /^release_[0-9]+\.[0-9]+\.[0-9]+/
      python: 3.7
      os: linux
      dist: xenial
      script: ./.travis_deploy.sh
    - stage: Test_deployed
      if: tag =~ /^release_[0-9]+\.[0-9]+\.[0-9]+/
      python: 3.8
      os: linux
      dist: bionic
      script:
        - ./.travis_install.sh
        - ./.travis_test.sh

before_install:
  - ./.travis_before_install.sh

install:
  - ./.travis_install.sh
